name: Build LaTeX and Create PR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile LaTeX files
        run: |
          mkdir -p build
          cd latex_src
          pdflatex -interaction=nonstopmode -output-directory=../build main.tex
          pdflatex -interaction=nonstopmode -output-directory=../build main.tex

      - name: Commit generated PDFs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build/*.pdf
          git commit -m "Add generated PDFs from LaTeX sources" || echo "No changes to commit"

      - name: Push changes to a new branch
        run: |
          BRANCH="generated-pdfs-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH
          git push origin $BRANCH
