name: Build LaTeX and Commit PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        run: sudo apt-get update

      - name: Compile LaTeX files
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: main.tex
          options: -cd ../../latex_src/
        
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-book
          path: main.pdf
