name: Build LaTeX and Commit PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./latex_src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        run: sudo apt-get update

      - name: Compile LaTeX files
        uses: antaljanosbenjamin/compile-latex@v1.0.0
        with:
    # The LaTeX file to be compiled, relative to the root of the repository.
          file: ./latex-src/main.tex
    # The directory for output files, relative to the root of the repository.
    
    # Additional arguments to pass over to latexmk.
    
          
          
        
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-book
          path: main.pdf
