name: Build LaTeX and Commit PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up LaTeX environment
      run: sudo apt-get update
    - name: Create empty .bbl file
      run: echo "% empty bibliography" > ./latex_src/main.bbl
    - name: LaTeX Action
      uses: fudan-mse/latex-action@v0.0.1
      continue-on-error: true
      with:
        root_file: main.tex
        working_directory: ./latex_src/
        args: -pdf -interaction=nonstopmode -bibtex- -f
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-book
        path: ./latex_src/main.pdf

